### ISSUE TITLE
[QUESTION] Css variables.

### ISSUE THREAD

**Issue by iSuslov** [Starcounter/Home#214]
Hi guys, I don't know about the configuration of the server I'm running, but maybe you have the idea. Basically when I import css in html component any css variable disappears: 

This:
```css
 paper-icon-button {
                    --paper-icon-button-ink-color: var(--paper-orange-500);
                    background-color: #03a9f4;
                    color: white;
                    border-radius: 3px;
                    padding: 2px;
                }
```

Becomes this:

```css
 paper-icon-button {
                    ;
                    background-color: #03a9f4;
                    color: white;
                    border-radius: 3px;
                    padding: 2px;
                }
```

Basically this works `border: 1px solid var(--paper-orange-500);` but this gets erased `--paper-icon-button-ink-color: var(--paper-orange-500);`
